// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutocompleteController from "./autocomplete_controller"
application.register("autocomplete", AutocompleteController)

import DismissibleController from "./dismissible_controller"
application.register("dismissible", DismissibleController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import ExpirableController from "./expirable_controller"
application.register("expirable", ExpirableController)

import FilesUploadController from "./files_upload_controller"
application.register("files-upload", FilesUploadController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import SlideoverController from "./slideover_controller"
application.register("slideover", SlideoverController)
